### PR TITLE
fix: Assign and delete single images

### LINKED ISSUE #380: Improve UI/UX of Assigning Single Images to Assignees
## Problem

There is currently no way for a user to assign assignees to single images - it currently is only clear for multiple images, either auto-assigned or individual input.

## Solution

A temporary fix was described in issue #352 - single image delete and update assignees (temporary fix).
To improve on this, the UI/UX could build upon issue #338 - assign single images update.

## Considered Alternatives

Could the solution exist within the individual image dialogue via the single icon? - this would require an icon update!
Or think about the userflow of requiring a single image to be selected and placing the solution within that UI frame - this relates to the potential UI layout update.

## Additional Context

Relates to #337 - update assign multiple labels + users

### PR DESCRIPTION
**Pull request by SilviaZeta**
## Description
Make the assignment and deletion of single images easier (see gliff-ai/curate#380 and gliff-ai/curate#352 for more info). At the moment these operations can only be performed with active "select multiple images" toggle.

fix: Changed the delete/assign images card, so as this is always shown in the toolbar; changed the metadata drawer so this is displayed any time a single image is selected with deselect multi-image mode; 
refactor: Deleted the `openImageUid` state as unnecessary
fix: Changed how image selection works to allow for multiple images to be selected without using shortcuts when in "multi-image-selection" mode, otherwise multiple-image selection doesn't work on tablets.

closes gliff-ai/curate#380

## Checklist:

Put an `x` in the boxes that apply to this pull request (you can also fill these out after opening the pull request). If you're unsure about any of these, don't hesitate to leave a comment on this pull request!

- [ ] I have read the gliff.ai Contribution Guide.
- [x] I have requested to **pull a branch** and not from main.
- [ ] I have checked all commit message styles match the requested structure.
- [ ] My code follows the style guidelines of this project.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have performed a self-review of my own code.
- [x] I have assigned **3 or less** reviewers.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] My changes generate no new warnings.
- [ ] I have made corresponding changes to the documentation.
- [ ] New database changes have been committed.
- [ ] If appropriate, I have bumped any version numbers.

### CODE REVIEW

**Review by joshuajames-smith — CHANGES_REQUESTED** [review]
- [x] Could you make the `Delete` icon disabled (colour: grey) when 0 images are selected?
- [x] The bug is still active meaning I can not select multiple images without the shortcut which users currently do not have access to find (shortcuts dialogue awaiting implementation). Once the `Select Multiple Images` toggle is active this should allow users to select multiple images!

**Comment by SilviaZeta** [comment]
Given that the card showing the selected images is always part of the UI and the only use of the "Select Multiple Images" is now to switch between the two different side-toolbars, one with the search-and-filter tools, the other with the metadata drawer (this provided a single image is selected), doesn't the "Select Multiple Images" button need repurposing?

**Comment by SilviaZeta** [comment]
> > Given that the card showing the selected images is always part of the UI and the only use of the "Select Multiple Images" is now to switch between the two different side-toolbars, one with the search-and-filter tools, the other with the metadata drawer (this provided a single image is selected), doesn't the "Select Multiple Images" button need repurposing?
> 
> @SilviaZeta I am having a re-think of this system as part of my larger CURATE update/re-think! The bug still remains however that once the `Select Multiple Images` toggle is selected, it does not actually allow a user to select multiple images? It should allow this!

It does work with widely used shortcuts (click on one image, then holding SHIFT, click on a second image to select all images in the range and Command/CTRL + click on any image to select/deselect), so not really a bug. It just doesn't work with mouse drag. Are you suggesting to implement select by mouse drag?

**Comment by SilviaZeta** [comment]
> > It does work with widely used shortcuts (click on one image, then holding SHIFT, click on a second image to select all images in the range and Command/CTRL + click on any image to select/deselect), so not really a bug. It just doesn't work with mouse drag. Are you suggesting to implement select by mouse drag?
> 
> Hi @SilviaZeta - I think the point is that when you've clicked a "select multiple" button, and it's highlighted as on, you shouldn't have to press any keyboard keys to select multiple. The whole reason for adding this button in the first place is tablets - where there is no keyboard. You should be able to click "Select Multiple" and then be able to select multiple just by clicking with the mouse, right?

Ah, makes sense! Sorry, didn't think about tablets.

**Review by ChasNelson1990 — APPROVED** [review]

**Review by joshuajames-smith — APPROVED** [review]

**Pull request merged**
