### PR TITLE
test: Access for owners and collaborators

### PR DESCRIPTION
**Pull request by SilviaZeta**
## Description
adds tests on access for owners and collaborators and fixes a couple of things (see commits).

addresses gliff-ai/dominate/issues/384

## Dependency changes
no

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New migrations have been committed
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] If appropriate, I have bumped any version numbers

### CODE REVIEW

**Comment by cooper667** [comment]
Fixes #384 😁

**Comment by ChasNelson1990** [comment]
Well it seems to have skipped the Percy action....... could be that I broke it.... could be that it's ignoring it because it's a draft like I intended... @SilviaZeta when will you be ready to make Ready for Review?

**Comment by SilviaZeta** [comment]
> Well it seems to have skipped the Percy action....... could be that I broke it.... could be that it's ignoring it because it's a draft like I intended... @SilviaZeta when will you be ready to make Ready for Review?

**Comment by ChrisBaidoo** [comment]
Screenshot 2021-11-22 at 15 20 24

We've somehow lost the hover effect on the sort button

**Review by philipjackson — DISMISSED** [review]

**Review by cooper667 — APPROVED** [review]

**Review by ChrisBaidoo — APPROVED** [review]

**Pull request merged**
