### PR TITLE
Fix publishing build

### PR DESCRIPTION
**Pull request by cooper667**
I just spent *WAY* too long on Manage trying to work out why I was publishing an empty folder

### CODE REVIEW

**Review by ChrisBaidoo — APPROVED** [review]

**Review by SilviaZeta — APPROVED** [review]

**Comment by SilviaZeta** [comment]
"prepublishOnly" instead of "prePublishOnly" 👀 !?

**Review by philipjackson — APPROVED** [review]

**Comment by ChasNelson1990** [comment]
@cooper667 this has been approved for a while now - just pulled in main, are you happy to merge if that doesn't break things?

**Review by ChasNelson1990 — APPROVED** [review]

**Comment by cooper667** [comment]
> @cooper667 this has been approved for a while now - just pulled in main, are you happy to merge if that doesn't break things?

Looks like they're in main already, maybe via another PR?

**Comment by cooper667** [comment]
I snuck it in with dependabot it seems

**Pull request closed without merging**
