### PR TITLE
feat: Material UI v5 migrate

### LINKED ISSUE #319: Material UI v5 migrate
Migrate to Material UI v5

### PR DESCRIPTION
**Pull request by ChrisBaidoo**
## Description

Migrate Annotate to MaterialUI v5

closes #319 

## Dependency Changes (delete if not applicable)
"@material-ui/core": "^4.11.3",
"@material-ui/icons": "^4.11.2",
"@material-ui/lab": "^4.0.0-alpha.58",
"@emotion/react": "^11.7.1",
"@emotion/styled": "^11.6.0",
"@mui/icons-material": "^5.2.5",
"@mui/lab": "^5.0.0-alpha.64",
"@mui/material": "^5.2.8",
"@mui/styles": "^5.2.3",

## Checklist:

Put an `x` in the boxes that apply to this pull request (you can also fill these out after opening the pull request). If you're unsure about any of these, don't hesitate to leave a comment on this pull request!

- [x] I have read the gliff.ai Contribution Guide.
- [x] I have requested to **pull a branch** and not from main.
- [x] I have checked all commit message styles match the requested structure.
- [x] My code follows the style guidelines of this project.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have performed a self-review of my own code.
- [x] I have assigned **3 or less** reviewers.
- [x] New and existing unit tests pass locally with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] My changes generate no new warnings.
- [ ] I have made corresponding changes to the documentation.
- [ ] New database changes have been committed.
- [ ] If appropriate, I have bumped any version numbers.

### CODE REVIEW

**Comment by cooper667** [comment]
Can likely remove `@mui/lab`?

**Review by cooper667 — DISMISSED** [review]

**Comment by cooper667** [comment]
Make sure it's labelled a breaking change, and don't merge until we're ready to use it upstream

**Comment by cooper667** [comment]
Some minor spacing stuff in Percy @joshuajames-smith might have thoughts on 😁

**Review by joshuajames-smith — CHANGES_REQUESTED** [review]
Just a couple small things in terms of design, it's just some minor spacing issues!

- [x] The space between the image grid and tools on the left is very close. Can this be more balanced such as the same gap between UI elements and the edge on the left?
- [x] The image grid ideally should have same gap between rows and columns so it sits nice visually to the users eye!

Screenshot 2022-01-26 at 14 01 44

I think there is also some Percy test edits which would be beneficial!

- [x] Could we change the size of the snapshots to 1024px and 1440px to match our expected tablet and desktop rendering? The mobile 375px is not needed for us!
- [x] There is also one Percy issue where it seems to show the whole page length of the `Large Image Grid Size` rather than only displaying the desktop cut-off view?

**Review by cooper667 — COMMENTED** [review]
Current version of Style is 8.0.0 (?!?!) so this should bump to that?

**Review by joshuajames-smith — CHANGES_REQUESTED** [review]
Thanks for fixing my initial comments! I think I have a final two changes? But let me know if you think it's worth creating new issues for them so we can close this PR!

- [x] When the `Annotation Labels [dropdown]` is open, the bar increases in size when ideally it should stay the same size just change colour?
Screenshot 2022-02-02 at 14 26 25
Screenshot 2022-02-02 at 14 26 41

- [x] The `Assign Users` icon moves once a user clicks an image when `Select Multiple Image` is active?
Screenshot 2022-02-02 at 14 27 55
Screenshot 2022-02-02 at 14 28 08

**Review by cooper667 — COMMENTED** [review]
`"@mui/lab":`

still needs removing

**Review by cooper667 — APPROVED** [review]

**Review by joshuajames-smith — APPROVED** [review]

**Pull request merged**
